; Make file for ENTERPRISE_VIDEOS (levelten APP)
api = 2
core = 7.x

; Modules included every time
projects[enterprise_video][version] = 1.0-alpha5
projects[enterprise_video][subdir] = contrib

projects[enterprise_base][version] = 1.0-beta11
projects[enterprise_base][subdir] = contrib

projects[media][version] = 1.1
projects[media][subdir] = contrib

projects[media_youtube][version] = 1.0-beta3
projects[media_youtube][subdir] = contrib

projects[views_media_browser][version] = 1.0
projects[views_media_browser][subdir] = contrib

