; Make file for ENTERPRISE_LOCATION (levelten APP)
api = 2
core = 7.x

; Modules included every time
projects[enterprise_location][version] = 1.0-beta4
projects[enterprise_location][subdir] = contrib

projects[addressfield][version] = 1.0-beta2 
projects[addressfield][subdir] = contrib

projects[geocoder][version] = 1.0
projects[geocoder][subdir] = contrib

projects[geofield][version] = 1.0
projects[geofield][subdir] = contrib

projects[geophp][version] = 1.4
projects[geophp][subdir] = contrib

