; Make file for ENTERPRISE_BLOG (levelten APP)
api = 2
core = 7.x

; Modules included every time
projects[features][version] = 1.0-rc2
projects[features][subdir] = contrib
projects[enterprise_blog][version] = 1.0-rc1
projects[enterprise_blog][subdir] = contrib

; Placement overrides
projects[realname][subdir] = contrib
projects[save_draft][subdir] = contrib
projects[scheduler][subdir] = contrib
projects[views_bulk_operations][subdir] = contrib
