; Make file for SEOTOOLS (levelten APP)
api = 2
core = 7.x

; Modules included every time
projects[seotools][version] = 1.0-alpha5
projects[seotools][subdir] = contrib
projects[alchemy][version] = 1.0-beta1
projects[alchemy][subdir] = contrib
projects[chart][version] = 1.1
projects[chart][subdir] = contrib
projects[contentanalysis][version] = 1.0-beta5
projects[contentanalysis][subdir] = contrib
projects[contentoptimizer][version] = 2.0-beta4
projects[contentoptimizer][subdir] = contrib
projects[globalredirect][version] = 1.4
projects[globalredirect][subdir] = contrib
projects[google_analytics][version] = 1.2
projects[google_analytics][subdir] = contrib
projects[kwresearch][version] = 1.0-alpha3
projects[kwresearch][subdir] = contrib
projects[page_title][version] = 2.7
projects[page_title][subdir] = contrib
projects[pathauto][version] = 1.0
projects[pathauto][subdir] = contrib
projects[tutorials][version] = 1.0-beta3
projects[tutorials][subdir] = contrib
projects[wordstream][version] = 1.0-rc1
projects[wordstream][subdir] = contrib
projects[xmlsitemap][version] = 2.0-rc1
projects[xmlsitemap][subdir] = contrib

